[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "docker-manager-backend"
version = "0.1.0"
description = "FastAPI backend for docker-manager"
requires-python = ">=3.8"

[tool.setuptools]
packages = ["app"]

[tool.black]
include = '\.pyi?$'
exclude = '''
/(
    \.git
    build
    install
    log
)/
'''

[tool.ruff]
line-length = 88

[tool.ruff.lint]
ignore = [ "D100", "D107", "D104", "COM812" ]
select = [
    # pycodestyle
    "E",
    "W",
    # pyflakes
    "F",
    # isort
    "I",
    # flake8 quotes
    "Q",
    # flake8 commas
    "COM",
    # flake8 comprehensions
    "C4",
    # pydocstyle, uncomment
    # "D",
    # pyupgrade
    "UP",

]

[tool.ruff.lint.pydocstyle]
convention = "google"

[tool.ruff.lint.per-file-ignores]
"test/*.py" = ["D103"]

[tool.pytest.ini_options]
addopts = "-v -s --cov=app --cov-report=xml:coverage.xml --cov-report=html:htmlcov --junitxml=junit.xml"
testpaths = ["tests"]
python_files = ["test_*.py", "*_test.py"]
python_classes = ["Test*"]
python_functions = ["test_*"]
